<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Eric Cayeux</Authors>
		<Company>Open Source Drilling Community</Company>
		<RootNamespace>OSDC.Drilling.Trajectory.ModelSharedOut</RootNamespace>
		<AssemblyName>OSDC.Drilling.Trajectory.ModelSharedOut</AssemblyName>
		<Title>Auto-generation of the API of the Trajectory microservice (distributed shared model approach)</Title>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.OpenApi.Readers" Version="1.6.28" />
		<PackageReference Include="NSwag.CodeGeneration.CSharp" Version="14.6.2" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0-1.final" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="PseudoConstructorsWriter.cs" />
	</ItemGroup>

</Project>
