name: Build OSDC Trajectory and run tests

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build OSDC Trajectory service image
      run: docker build --file Service/Dockerfile --tag osdcdrillingtrajectoryservice:test .

    - name: Run OSDC Trajectory service container
      run: docker run --detach --name osdc-trajectory-service-test --publish 8080:8080 osdcdrillingtrajectoryservice:test

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration 'Release'

    - name: Run ServiceTest & ModelTest
      run: dotnet test --no-build --verbosity normal --configuration 'Release'
